import ExecutiveWorkspace from "../../components/layout/ExecutiveWorkspace";
import WorkspaceSection from "../../components/business/WorkspaceSection";

import OpportunityPipeline from "../../components/execution/OpportunityPipeline";
import ExecutionQueue from "../../components/execution/ExecutionQueue";

import { getExecutionWorkspace, getUserContext } from "../../lib/services";
import { opportunityPipeline } from "../../data/executions";

export default function ExecutionPage() {
  const user = getUserContext();
  const workspace = getExecutionWorkspace(user);

  const { execution } = workspace;

  return (
    <ExecutiveWorkspace
      eyebrow="Execution Workspace"
      title="Execution"
      decision="Which recommendations are ready to execute, in progress, or need follow-up?"
    >

      <WorkspaceSection
        label="Pipeline"
        title="Opportunity Pipeline"
        description="Track operational opportunities as they move from recommendation to execution."
      >
        <OpportunityPipeline stages={opportunityPipeline} />
      </WorkspaceSection>

      <WorkspaceSection
        label="Execution"
        title="Active Playbooks"
        description="Recommended operational actions generated by Syntrix."
      >
        <ExecutionQueue executions={execution.items} />
      </WorkspaceSection>
    </ExecutiveWorkspace>
  );
}