import AppLayout from "../../components/layout/AppLayout";
import WorkspacePage from "../../components/layout/WorkspacePage";
import WorkspaceHeader from "../../components/business/WorkspaceHeader";
import WorkspaceSection from "../../components/business/WorkspaceSection";

import OpportunityPipeline from "../../components/execution/OpportunityPipeline";
import ExecutionQueue from "../../components/execution/ExecutionQueue";

import { getExecutionWorkspace, getUserContext } from "../../lib/services";
import { opportunityPipeline } from "../../data/executions";

export default function ExecutionPage() {
  const user = getUserContext();
  const workspace = getExecutionWorkspace(user);

  const { execution } = workspace;

  return (
    <AppLayout>
      <WorkspacePage>
        <WorkspaceHeader
          eyebrow="Execution Workspace"
          title="Execution Playbooks"
          decision="What work is currently in progress and what should happen next?"
          updatedAt="Updated live"
        />

        <WorkspaceSection
          label="Pipeline"
          title="Opportunity Pipeline"
          description="Track operational opportunities as they move from recommendation to execution."
        >
          <OpportunityPipeline stages={opportunityPipeline} />
        </WorkspaceSection>

        <WorkspaceSection
          label="Execution"
          title="Active Playbooks"
          description="Recommended operational actions generated by Syntrix."
        >
          <ExecutionQueue executions={execution.items} />
        </WorkspaceSection>
      </WorkspacePage>
    </AppLayout>
  );
}